character:
  path: "./characters/data_agent.json"

database:
  type: "sqlite"
  path: "./data/agent.db"

llm:
  provider: "openai"
  base_url: "https://api.openai.com/v1"

data:
  carvid:
    url: "https://api.carv.io"